
groups:
- name: general
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.job }} target {{ $labels.instance }} has been down for >2m"

  - alert: HighHTTP5xx
    expr: sum(rate(http_server_requests_seconds_count{status=~"5.."}[5m])) by (job) > 5
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High 5xx rate on {{ $labels.job }}"
      description: "5xx errors > 5 req/min for 10m"
